FROM dolfin_dic-dev

WORKDIR /home/fenics/code
RUN git clone https://gitlab.inria.fr/mgenet/myPythonLibrary.git
RUN git clone https://gitlab.inria.fr/mgenet/myVTKPythonLibrary.git
RUN git clone https://gitlab.inria.fr/mgenet/vtkpython_cbl.git
RUN git clone https://gitlab.inria.fr/mgenet/dolfin_cm.git
RUN git clone https://gitlab.inria.fr/mgenet/dolfin_dic.git
