FROM dolfin_dic-dev

WORKDIR /home/fenics/code
RUN git clone https://github.com/mgenet/myPythonLibrary.git
RUN git clone https://github.com/mgenet/myVTKPythonLibrary.git
RUN git clone https://github.com/mgenet/vtkpython_cbl.git
RUN git clone https://bitbucket.org/mgenet/dolfin_dic.git
